In [5]:
import numpy as np

In [7]:
array_one = np.array([0,1,3,5,7,9])
array_one

array([0, 1, 3, 5, 7, 9])

In [8]:
num = [11,22,33,44,55,66,77]
array_two = np.array(num)
array_two

array([11, 22, 33, 44, 55, 66, 77])

In [10]:
array_of_zeros = np.zeros((2,3))#will creare a array of dimension 2,3 of zero
array_of_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
array_of_ones = np.ones((2,3))#will creare a array of dimension 2,3 of zero
#defaul will be type float
array_of_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
array_of_ones = np.ones((3,2), dtype = np.int32)
array_of_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [13]:
array_empty = np.empty((3,2))
array_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
array_eye = np.eye(4) # use to create identity matrix
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
array_of_evens = np.arange(2,24,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [17]:
array_of_flots = np.arange(1,3,0.3)
array_of_flots

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

In [19]:
array_2d = np.array([(3,4,6),(2,1,6)])
array_2d

array([[3, 4, 6],
       [2, 1, 6]])

In [20]:
array_2d.shape

(2, 3)

In [21]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
array_nd = np.arange(6).reshape(2,3)

In [28]:
array_nd

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
np.ones_like(array_nd)

array([[1, 1, 1],
       [1, 1, 1]])