In [1]:
import numpy as np

In [2]:
p = np.array([9, 8, 7])
q = np.array([3, 2, 4])

In [3]:
p + q #element by element addition

array([12, 10, 11])

In [4]:
p - q

array([6, 6, 3])

In [5]:
p % 2

array([1, 0, 1], dtype=int32)

In [6]:
p > 8

array([ True, False, False])

In [8]:
x = np.array([[2, 1], [1, 3]])
y = np.array([[3, 2],[4, 2]])
print('x: \n', x)
print('y: \n', y)

x: 
 [[2 1]
 [1 3]]
y: 
 [[3 2]
 [4 2]]


In [9]:
x + y

array([[5, 3],
       [5, 5]])

In [10]:
x.dot(y)

array([[10,  6],
       [15,  8]])

In [12]:
x *= 4

In [13]:
print(x)

[[ 8  4]
 [ 4 12]]


In [21]:
fleet_milages = np.array([11231, 12245, 11412, 31231, 14356])

print('Sum: ', fleet_milages.sum())
print('smallest milage: ' , fleet_milages.min())
print('Max milage: ', fleet_milages.max())
print('Average milage: ', fleet_milages.mean())

Sum:  80475
smallest milage:  11231
Max milage:  31231
Average milage:  16095.0
