In [1]:
import numpy as np

In [3]:
circle_redii = np.array([145, 120, 90, 60, 45, 30])
circle_diamter = circle_redii * 2
circle_diamter

array([290, 240, 180, 120,  90,  60])

In [4]:
circle_area = np.pi * circle_redii**2
circle_area

array([66051.98554173, 45238.93421169, 25446.90049408, 11309.73355292,
        6361.72512352,  2827.43338823])

In [5]:
angle_degree = np.array([0 , 30 , 60 , 90, 120, 150, 180])

In [7]:
angle_redian = angle_degree * np.pi /180
angle_redian

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265])

In [8]:
print ('sine value')
np.sin(angle_redian)

sine value


array([0.00000000e+00, 5.00000000e-01, 8.66025404e-01, 1.00000000e+00,
       8.66025404e-01, 5.00000000e-01, 1.22464680e-16])

In [9]:
print ('cos values')
np.cos(angle_redian)

cos values


array([ 1.00000000e+00,  8.66025404e-01,  5.00000000e-01,  6.12323400e-17,
       -5.00000000e-01, -8.66025404e-01, -1.00000000e+00])

In [10]:
print ('tan values')
np.tan(angle_redian)

tan values


array([ 0.00000000e+00,  5.77350269e-01,  1.73205081e+00,  1.63312394e+16,
       -1.73205081e+00, -5.77350269e-01, -1.22464680e-16])

In [11]:
sine_values = np.sin(angle_redian)

In [13]:
arcsine_values = np.arcsin(sine_values)
print(arcsine_values)

[0.00000000e+00 5.23598776e-01 1.04719755e+00 1.57079633e+00
 1.04719755e+00 5.23598776e-01 1.22464680e-16]


In [14]:
x = np.arange(4, 31, 5)
x

array([ 4,  9, 14, 19, 24, 29])

In [15]:
expo = np.exp(x)
expo

array([5.45981500e+01, 8.10308393e+03, 1.20260428e+06, 1.78482301e+08,
       2.64891221e+10, 3.93133430e+12])

In [16]:
sqrt = np.sqrt(x)
sqrt

array([2.        , 3.        , 3.74165739, 4.35889894, 4.89897949,
       5.38516481])

In [17]:
float_values = np.genfromtxt('datasets/float_values.csv', delimiter= ',')

In [18]:
float_values

array([0.8944, 0.8898, 0.8894, ..., 0.7051, 0.6992, 0.7047])

In [20]:
float_values.shape

(5998,)

In [25]:
print('Mean = %i' %np.mean(float_values))
print('Median = %i' %np.median(float_values))
print('Variance = %i' %np.var(float_values))
print('Standard Deviation = %i' %np.std(float_values))

Mean = 16
Median = 5
Variance = 1659
Standard Deviation = 40
